### ISSUE TITLE
Latest Game Server Errors

### ISSUE THREAD

**Issue by JevLOMCN** [damianday/Conquer#25]
This error appears when someone gets to the "Gates" and will stop any player joining the world.
[07/05/2024 21:31:10] Asynchronous connection exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GameServer.Database.SystemInfo.get_Info() in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Database\SystemInfo.cs:line 86
   at GameServer.Networking.NetworkManager.Connection(IAsyncResult result) in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Networking\NetworkManager.cs:line 120

CS Line 120 - if (!SystemInfo.Info.IPBans.ContainsKey(ip) || SystemInfo.Info.IPBans[ip] < SEngine.CurrentTime)

**Comment by damianday** [comment]
Appears to be a database error, will check latest is updated and correct. A stat was renamed.
    MonsterDamage = 112,    // 怪物伤害
