### ISSUE TITLE
Latest GameServer Error

### ISSUE THREAD

**Issue by JevLOMCN** [damianday/Conquer#32]
TargetSite:
Void AddBuff(UInt16, GameServer.Map.MapObject)
HelpLink:

InnerException:

Source:
GameServer
Message:
Object reference not set to an instance of an object.
StackTrace:
   at GameServer.Map.MapObject.AddBuff(UInt16 id, MapObject target) in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Map\MapObject.cs:line 800
   at GameServer.Map.MonsterObject.Resurrect(Boolean calculate) in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Map\MonsterObject.cs:line 1662
   at GameServer.Map.MonsterObject..ctor(MonsterInfo info, Map map, Int32 resInterval, Point location, Int32 range, Boolean forbidResurrection, Boolean refreshNow) in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Map\MonsterObject.cs:line 267
   at GameServer.Map.MapManager.Initialize() in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Map\MapManager.cs:line 676
   at GameServer.SEngine.ServiceThreadLoop() in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer\SEngine.cs:line 154

**Comment by JevLOMCN** [comment]
My fault, I didn't transfer over the latest Database.
