### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JevLOMCN** [damianday/Conquer#38]
Game server Error:
[15/05/2024 16:48:39] Asynchronous connection exception: System.ArgumentException: Value does not fall within the expected range. (Parameter 'asyncResult')
   at System.Threading.Tasks.TaskToAsyncResult.Unwrap[TResult](IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskToAsyncResult.End[TResult](IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptCore[TResult](IAsyncResult asyncResult)
   at GameServer.Networking.NetworkManager.StatusConnection(IAsyncResult result) in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Networking\NetworkManager.cs:line 206

Client side Error:
![image](https://github.com/damianday/Conquer/assets/68875342/87e9408c-55d2-4b4f-8918-0980c25ecfbf)

**Comment by JevLOMCN** [comment]
Was old launcher causing this.
