### ISSUE TITLE
Database Error with EN db

### ISSUE THREAD

**Issue by JevLOMCN** [damianday/Conquer#40]
Game Server with CN Database:

[15/05/2024 21:07:14] Connecting to 'System' database
[15/05/2024 21:07:14] Loading system data...
[15/05/2024 21:07:15] MonsterInfo Template loaded, Total: 2323
[15/05/2024 21:07:15] GuardInfo Template loaded, Total: 923
[15/05/2024 21:07:15] NpcDialog Template loaded, Total: 798
[15/05/2024 21:07:15] GameMap Template loaded, Total: 177
[15/05/2024 21:07:15] Terrain Template loaded, Total: 192
[15/05/2024 21:07:15] MapArea Template loaded, Total: 206
[15/05/2024 21:07:15] TeleportGate Template loaded, Total: 557
[15/05/2024 21:07:15] MonsterSpawn Template loaded, Total: 215
[15/05/2024 21:07:15] MonsterBossTimedZen Template loaded, Total: 124
[15/05/2024 21:07:15] MapGuard Template loaded, Total: 1070
[15/05/2024 21:07:16] GameItem Template loaded, Total: 4203
[15/05/2024 21:07:16] RandomStats Template loaded, Total: 0
[15/05/2024 21:07:16] EquipmentStats Template loaded, Total: 13
[15/05/2024 21:07:16] GameStore Template loaded, Total: 84
[15/05/2024 21:07:16] RareTreasureItem Template loaded, Total: 57
[15/05/2024 21:07:16] GameTitle Template loaded, Total: 68
[15/05/2024 21:07:16] InscriptionSkill Template loaded, Total: 396
[15/05/2024 21:07:16] GameSkill Template loaded, Total: 1302
[15/05/2024 21:07:16] SkillTrap Template loaded, Total: 749
[15/05/2024 21:07:17] GameBuff Template loaded, Total: 3128
[15/05/2024 21:07:17] GameMount Template loaded, Total: 25
[15/05/2024 21:07:17] ItemSetInfo Template loaded, Total: 0
[15/05/2024 21:07:17] MountStats Template loaded, Total: 0
[15/05/2024 21:07:17] ItemCrafting Template loaded, Total: 0
[15/05/2024 21:07:17] System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'name')
Actual value was VIPID.
   at Microsoft.Data.Sqlite.SqliteDataRecord.GetOrdinal(String name)
   at SqlReaderExtension.GetValue[T](DbDataReader reader, String column, T defValue) in G:\Mir3DEMU\GitHub\Conquer\Common\SqlReaderExtension.cs:line 13
   at SqlReaderExtension.GetInt32(DbDataReader reader, String column, Int32 defValue) in G:\Mir3DEMU\GitHub\Conquer\Common\SqlReaderExtension.cs:line 24
   at GameServer.Template.VIPSystem.LoadData() in G:\Mir3DEMU\GitHub\Conquer\GameServer\GameServer.Template\VIPSystem.cs:line 47
[15/05/2024 21:07:17] VIPSystem Template loaded, Total: 0
[15/05/2024 21:07:17] TreasureChestInfo Template loaded, Total: 0
[15/05/2024 21:07:17] Administrator Template loaded, Total: 0
[15/05/2024 21:07:17] The system data load is complete
[15/05/2024 21:07:17] Loading user data...
[15/05/2024 21:07:17] MentorInfo Loaded, Quantity: 0
[15/05/2024 21:07:17] GuildInfo Loaded, Quantity: 0
[15/05/2024 21:07:17] TeamInfo Loaded, Quantity: 0
[15/05/2024 21:07:17] MailInfo Loaded, Quantity: 0
[15/05/2024 21:07:17] PetInfo Loaded, Quantity: 2
[15/05/2024 21:07:17] BuffInfo Loaded, Quantity: 2
[15/05/2024 21:07:17] SkillInfo Loaded, Quantity: 80
[15/05/2024 21:07:17] AccountInfo Loaded, Quantity: 26
[15/05/2024 21:07:17] SystemInfo Loaded, Quantity: 1
[15/05/2024 21:07:17] ItemInfo Loaded, Quantity: 117
[15/05/2024 21:07:17] EquipmentInfo Loaded, Quantity: 67
[15/05/2024 21:07:17] CharacterInfo Loaded, Quantity: 6
[15/05/2024 21:07:17] Start working on data correlation tasks...
[15/05/2024 21:07:17] Data correlation task processing completed, total number of tasks:170
[15/05/2024 21:07:17] Data Type:[ItemInfo], Internal Fields:[Owner], Total[107]Failed to correlate data
[15/05/2024 21:07:17] Data Type:[EquipmentInfo], Internal Fields:[Owner], Total[13]Failed to correlate data
[15/05/2024 21:07:17] Data Type:[AccountInfo], Internal Fields:[Characters], Total[20]Failed to correlate data
[15/05/2024 21:07:17] The user data is loaded

Game Server with EN Database: Stuck at Terrain

[15/05/2024 21:08:09] Connecting to 'System' database
[15/05/2024 21:08:09] Loading system data...
[15/05/2024 21:08:10] MonsterInfo Template loaded, Total: 2323
[15/05/2024 21:08:10] GuardInfo Template loaded, Total: 923
[15/05/2024 21:08:10] NpcDialog Template loaded, Total: 798
[15/05/2024 21:08:10] GameMap Template loaded, Total: 177

Game Server with EN Database (With CN terrain files): Stuck at GameItem

[15/05/2024 21:09:29] Connecting to 'System' database
[15/05/2024 21:09:29] Loading system data...
[15/05/2024 21:09:31] MonsterInfo Template loaded, Total: 2323
[15/05/2024 21:09:31] GuardInfo Template loaded, Total: 923
[15/05/2024 21:09:31] NpcDialog Template loaded, Total: 798
[15/05/2024 21:09:31] GameMap Template loaded, Total: 177
[15/05/2024 21:09:31] Terrain Template loaded, Total: 192
[15/05/2024 21:09:31] MapArea Template loaded, Total: 206
[15/05/2024 21:09:31] TeleportGate Template loaded, Total: 557
[15/05/2024 21:09:31] MonsterSpawn Template loaded, Total: 215
[15/05/2024 21:09:31] MonsterBossTimedZen Template loaded, Total: 124
[15/05/2024 21:09:31] MapGuard Template loaded, Total: 1070

Maybe Terrains (Maps) and Items are somewhere hard coded in the Game Server.
This will need to be adjusted to allow the use of an English Database.

[Database - EN.zip](https://github.com/damianday/Conquer/files/15326544/Database.-.EN.zip)

**Comment by damianday** [comment]
VIP database table columns have now been translated, just need to make sure the English db also has these translated column names

**Comment by damianday** [comment]
Also because more fields in character data was translated any old characters won't load, which is annoying..
